apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-config
spec:
  targetNamespace: nginx
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      version: 12.0.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-config
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # support values https://artifacthub.io/packages/helm/bitnami/nginx
  values:
    service:
      type: LoadBalancer
    replicaCount: 2
