apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-config
resources:
- ../sources
- ../base/timefeed
- ../base/aggregator
patches:
- target:
    group: kustomize.toolkit.fluxcd.io
    kind: Kustomization
    name: flux-config-timefeed
  patch: |-
    - op: replace
      path: /spec/path
      value: ./deploy/timefeed/staging 
    - op: replace
      path: /spec/targetNamespace
      value: staging
- target:
    group: kustomize.toolkit.fluxcd.io
    kind: Kustomization
    name: flux-config-aggregator
  patch: |-
    - op: replace
      path: /spec/path
      value: ./deploy/aggregator/staging 
