apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-config-aggregator
spec:
  interval: 5m
  targetNamespace: flux-config
  sourceRef:
    kind: GitRepository
    name: sample-apps
  path: ./deploy/aggregator/production
  prune: true
